sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QTFwR3Zoag4V0t61b8KR0aIVcsOZ6oAeJNUGWCIM2WbaFWngVFYE30xt0AmM34bQuZmdIK0SjBowuAotKeUG8dNtvTNvwL3NSZYL+3x68W++lv3LTbzxTEEXv0ql5uOUUN460o3xG0zKn/mMjvTo0H06S8hq6ZAM0gv/3XTLJUvM0ckYpAu8EkDHnWgTLoWeqxe15jFHCxfatkF5NW41YCuSJVV43VuszwMuaDKSi8PtIQzG4kHuguD//59z5xzwxB+9z0c150ci42QXM84l9A16jUz5BDXSS1HhnghiRexMUeEQFZ7z50R12VhEzcSQl9W4WyxVSebsKeKRyR4XHwAAFd88PuPUwgn655bK7P7S77yoivC0rzBwRodvEOqHy16VAu+E+8jDUAtzK3nF6/o1dD4xtIzWcWuIXiAzjYd5gukTFbuVsdKDA2qb57s5z6idEbf76eC1f3kQkch90O0NyzRxh//odTHb50MLuqSIPkr424WihymMy0UNTZHEj+9evVB//WxQlpWzTzNYab4vhwTgyo8P3EZj1xgAHU+UQFTQ3bPhlf4EvTd3eGkGN+Dqyq2XtJI/ZWTromYjIzuAwUdCoXv8KD7T+RGmsJJIhtLKj6e4BtDAYdkv7rpMY4Tg7O4yig23557VEAcFuC288dGOoGMzlY8ouvyfAEE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tom-Swift-and-His-Sky-Racer--Or-The-Quickest-Flight-on-Record_951
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy